// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetLikeListResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetLikeListResponse.pbobjc.h"
 #import "ErrorMessageResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetLikeListResponseRoot

@implementation GetLikeListResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ErrorMessageResponseRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GetLikeListResponseRoot_FileDescriptor

static GPBFileDescriptor *GetLikeListResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetLikeListResponseMessage

@implementation GetLikeListResponseMessage

@dynamic hasErrorMsg, errorMsg;
@dynamic isLastPage;
@dynamic likesArray, likesArray_Count;

typedef struct GetLikeListResponseMessage__storage_ {
  uint32_t _has_storage_[1];
  ErrorMessage *errorMsg;
  NSMutableArray *likesArray;
} GetLikeListResponseMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "errorMsg",
        .dataTypeSpecific.className = GPBStringifySymbol(ErrorMessage),
        .number = GetLikeListResponseMessage_FieldNumber_ErrorMsg,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetLikeListResponseMessage__storage_, errorMsg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "isLastPage",
        .dataTypeSpecific.className = NULL,
        .number = GetLikeListResponseMessage_FieldNumber_IsLastPage,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "likesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(LikeMessage),
        .number = GetLikeListResponseMessage_FieldNumber_LikesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetLikeListResponseMessage__storage_, likesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetLikeListResponseMessage class]
                                     rootClass:[GetLikeListResponseRoot class]
                                          file:GetLikeListResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetLikeListResponseMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\010\000\002\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - LikeMessage

@implementation LikeMessage

@dynamic userId;
@dynamic author;
@dynamic authorPhoto;
@dynamic createDt;

typedef struct LikeMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *author;
  NSString *authorPhoto;
  int64_t userId;
  int64_t createDt;
} LikeMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = LikeMessage_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(LikeMessage__storage_, userId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "author",
        .dataTypeSpecific.className = NULL,
        .number = LikeMessage_FieldNumber_Author,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(LikeMessage__storage_, author),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "authorPhoto",
        .dataTypeSpecific.className = NULL,
        .number = LikeMessage_FieldNumber_AuthorPhoto,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(LikeMessage__storage_, authorPhoto),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "createDt",
        .dataTypeSpecific.className = NULL,
        .number = LikeMessage_FieldNumber_CreateDt,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(LikeMessage__storage_, createDt),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[LikeMessage class]
                                     rootClass:[GetLikeListResponseRoot class]
                                          file:GetLikeListResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(LikeMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\006\000\003\013\000\004\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
