// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateProfileRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UpdateProfileRequest.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UpdateProfileRequestRoot

@implementation UpdateProfileRequestRoot

@end

#pragma mark - UpdateProfileRequestRoot_FileDescriptor

static GPBFileDescriptor *UpdateProfileRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UpdateProfileRequestMessage

@implementation UpdateProfileRequestMessage

@dynamic session;
@dynamic settingField;
@dynamic settingValue;
@dynamic photo;

typedef struct UpdateProfileRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  UpdateProfileRequestMessage_SettingField settingField;
  NSString *session;
  NSString *settingValue;
  NSData *photo;
} UpdateProfileRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = UpdateProfileRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UpdateProfileRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "settingField",
        .dataTypeSpecific.enumDescFunc = UpdateProfileRequestMessage_SettingField_EnumDescriptor,
        .number = UpdateProfileRequestMessage_FieldNumber_SettingField,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UpdateProfileRequestMessage__storage_, settingField),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "settingValue",
        .dataTypeSpecific.className = NULL,
        .number = UpdateProfileRequestMessage_FieldNumber_SettingValue,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UpdateProfileRequestMessage__storage_, settingValue),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "photo",
        .dataTypeSpecific.className = NULL,
        .number = UpdateProfileRequestMessage_FieldNumber_Photo,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(UpdateProfileRequestMessage__storage_, photo),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UpdateProfileRequestMessage class]
                                     rootClass:[UpdateProfileRequestRoot class]
                                          file:UpdateProfileRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UpdateProfileRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\014\000\003\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UpdateProfileRequestMessage_SettingField_RawValue(UpdateProfileRequestMessage *message) {
  GPBDescriptor *descriptor = [UpdateProfileRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UpdateProfileRequestMessage_FieldNumber_SettingField];
  return GPBGetMessageInt32Field(message, field);
}

void SetUpdateProfileRequestMessage_SettingField_RawValue(UpdateProfileRequestMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [UpdateProfileRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UpdateProfileRequestMessage_FieldNumber_SettingField];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum UpdateProfileRequestMessage_SettingField

GPBEnumDescriptor *UpdateProfileRequestMessage_SettingField_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "UserPhoto\000UserName\000UserGender\000UserAge\000Sm"
        "okeAge\000UserHeight\000UserWeight\000HomeInfo\000Pl"
        "anCount\000PlanTime\000Language\000";
    static const int32_t values[] = {
        UpdateProfileRequestMessage_SettingField_UserPhoto,
        UpdateProfileRequestMessage_SettingField_UserName,
        UpdateProfileRequestMessage_SettingField_UserGender,
        UpdateProfileRequestMessage_SettingField_UserAge,
        UpdateProfileRequestMessage_SettingField_SmokeAge,
        UpdateProfileRequestMessage_SettingField_UserHeight,
        UpdateProfileRequestMessage_SettingField_UserWeight,
        UpdateProfileRequestMessage_SettingField_HomeInfo,
        UpdateProfileRequestMessage_SettingField_PlanCount,
        UpdateProfileRequestMessage_SettingField_PlanTime,
        UpdateProfileRequestMessage_SettingField_Language,
    };
    static const char *extraTextFormatInfo = "\013\000$\245\000\001$\244\000\002$\246\000\003$\243\000\004%\243\000\005$\246\000\006$\246\000\007$\244\000\010$\245\000\t$\244\000\n(\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(UpdateProfileRequestMessage_SettingField)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:UpdateProfileRequestMessage_SettingField_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL UpdateProfileRequestMessage_SettingField_IsValidValue(int32_t value__) {
  switch (value__) {
    case UpdateProfileRequestMessage_SettingField_UserPhoto:
    case UpdateProfileRequestMessage_SettingField_UserName:
    case UpdateProfileRequestMessage_SettingField_UserGender:
    case UpdateProfileRequestMessage_SettingField_UserAge:
    case UpdateProfileRequestMessage_SettingField_SmokeAge:
    case UpdateProfileRequestMessage_SettingField_UserHeight:
    case UpdateProfileRequestMessage_SettingField_UserWeight:
    case UpdateProfileRequestMessage_SettingField_HomeInfo:
    case UpdateProfileRequestMessage_SettingField_PlanCount:
    case UpdateProfileRequestMessage_SettingField_PlanTime:
    case UpdateProfileRequestMessage_SettingField_Language:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
