// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadHeartRateDataRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UploadHeartRateDataRequest.pbobjc.h"
 #import "HeartRateData.pbobjc.h"
 #import "PhoneType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UploadHeartRateDataRequestRoot

@implementation UploadHeartRateDataRequestRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[HeartRateDataRoot extensionRegistry]];
    [registry addExtensions:[PhoneTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UploadHeartRateDataRequestRoot_FileDescriptor

static GPBFileDescriptor *UploadHeartRateDataRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UploadHeartRateDataRequestMessage

@implementation UploadHeartRateDataRequestMessage

@dynamic session;
@dynamic phoneType;
@dynamic heartRateDatasArray, heartRateDatasArray_Count;

typedef struct UploadHeartRateDataRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  PhoneType phoneType;
  NSString *session;
  NSMutableArray *heartRateDatasArray;
} UploadHeartRateDataRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = UploadHeartRateDataRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UploadHeartRateDataRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneType",
        .dataTypeSpecific.enumDescFunc = PhoneType_EnumDescriptor,
        .number = UploadHeartRateDataRequestMessage_FieldNumber_PhoneType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UploadHeartRateDataRequestMessage__storage_, phoneType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "heartRateDatasArray",
        .dataTypeSpecific.className = GPBStringifySymbol(HeartRateDataMessage),
        .number = UploadHeartRateDataRequestMessage_FieldNumber_HeartRateDatasArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UploadHeartRateDataRequestMessage__storage_, heartRateDatasArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UploadHeartRateDataRequestMessage class]
                                     rootClass:[UploadHeartRateDataRequestRoot class]
                                          file:UploadHeartRateDataRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UploadHeartRateDataRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\t\000\003\000heartRateDatas\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UploadHeartRateDataRequestMessage_PhoneType_RawValue(UploadHeartRateDataRequestMessage *message) {
  GPBDescriptor *descriptor = [UploadHeartRateDataRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UploadHeartRateDataRequestMessage_FieldNumber_PhoneType];
  return GPBGetMessageInt32Field(message, field);
}

void SetUploadHeartRateDataRequestMessage_PhoneType_RawValue(UploadHeartRateDataRequestMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [UploadHeartRateDataRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UploadHeartRateDataRequestMessage_FieldNumber_PhoneType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
