// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadHeartRateDataRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class HeartRateDataMessage;
GPB_ENUM_FWD_DECLARE(PhoneType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UploadHeartRateDataRequestRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface UploadHeartRateDataRequestRoot : GPBRootObject
@end

#pragma mark - UploadHeartRateDataRequestMessage

typedef GPB_ENUM(UploadHeartRateDataRequestMessage_FieldNumber) {
  UploadHeartRateDataRequestMessage_FieldNumber_Session = 1,
  UploadHeartRateDataRequestMessage_FieldNumber_PhoneType = 2,
  UploadHeartRateDataRequestMessage_FieldNumber_HeartRateDatasArray = 3,
};

@interface UploadHeartRateDataRequestMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *session;

@property(nonatomic, readwrite) enum PhoneType phoneType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HeartRateDataMessage*> *heartRateDatasArray;
/// The number of items in @c heartRateDatasArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger heartRateDatasArray_Count;

@end

/// Fetches the raw value of a @c UploadHeartRateDataRequestMessage's @c phoneType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t UploadHeartRateDataRequestMessage_PhoneType_RawValue(UploadHeartRateDataRequestMessage *message);
/// Sets the raw value of an @c UploadHeartRateDataRequestMessage's @c phoneType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetUploadHeartRateDataRequestMessage_PhoneType_RawValue(UploadHeartRateDataRequestMessage *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
