// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBlogListResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetBlogListResponse.pbobjc.h"
 #import "ErrorMessageResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetBlogListResponseRoot

@implementation GetBlogListResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ErrorMessageResponseRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GetBlogListResponseRoot_FileDescriptor

static GPBFileDescriptor *GetBlogListResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetBlogListResponseMessage

@implementation GetBlogListResponseMessage

@dynamic hasErrorMsg, errorMsg;
@dynamic isLastPage;
@dynamic blogsArray, blogsArray_Count;

typedef struct GetBlogListResponseMessage__storage_ {
  uint32_t _has_storage_[1];
  ErrorMessage *errorMsg;
  NSMutableArray *blogsArray;
} GetBlogListResponseMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "errorMsg",
        .dataTypeSpecific.className = GPBStringifySymbol(ErrorMessage),
        .number = GetBlogListResponseMessage_FieldNumber_ErrorMsg,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlogListResponseMessage__storage_, errorMsg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "isLastPage",
        .dataTypeSpecific.className = NULL,
        .number = GetBlogListResponseMessage_FieldNumber_IsLastPage,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "blogsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(BlogMessage),
        .number = GetBlogListResponseMessage_FieldNumber_BlogsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetBlogListResponseMessage__storage_, blogsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlogListResponseMessage class]
                                     rootClass:[GetBlogListResponseRoot class]
                                          file:GetBlogListResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlogListResponseMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\010\000\002\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BlogMessage

@implementation BlogMessage

@dynamic blogId;
@dynamic content;
@dynamic longitude;
@dynamic latitude;
@dynamic address;
@dynamic likeCount;
@dynamic commentCount;
@dynamic userId;
@dynamic isLike;
@dynamic author;
@dynamic authorPhoto;
@dynamic createDt;
@dynamic imagesArray, imagesArray_Count;

typedef struct BlogMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t likeCount;
  int32_t commentCount;
  NSString *content;
  NSString *address;
  NSString *author;
  NSString *authorPhoto;
  NSMutableArray *imagesArray;
  int64_t blogId;
  double longitude;
  double latitude;
  int64_t userId;
  int64_t createDt;
} BlogMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "blogId",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_BlogId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, blogId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_Content,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, content),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_Longitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_Latitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "address",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_Address,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, address),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "likeCount",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_LikeCount,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, likeCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "commentCount",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_CommentCount,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, commentCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_UserId,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, userId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "isLike",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_IsLike,
        .hasIndex = 8,
        .offset = 9,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "author",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_Author,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, author),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "authorPhoto",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_AuthorPhoto,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, authorPhoto),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "createDt",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_CreateDt,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, createDt),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "imagesArray",
        .dataTypeSpecific.className = NULL,
        .number = BlogMessage_FieldNumber_ImagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(BlogMessage__storage_, imagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BlogMessage class]
                                     rootClass:[GetBlogListResponseRoot class]
                                          file:GetBlogListResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BlogMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\001\006\000\006\t\000\007\014\000\010\006\000\t\006\000\013\013\000\014\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
