// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ErrorMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LoginResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface LoginResponseRoot : GPBRootObject
@end

#pragma mark - LoginResponseMessage

typedef GPB_ENUM(LoginResponseMessage_FieldNumber) {
  LoginResponseMessage_FieldNumber_ErrorMsg = 1,
  LoginResponseMessage_FieldNumber_Session = 2,
  LoginResponseMessage_FieldNumber_UserId = 3,
  LoginResponseMessage_FieldNumber_Phone = 4,
  LoginResponseMessage_FieldNumber_UserName = 5,
  LoginResponseMessage_FieldNumber_UserPhoto = 6,
  LoginResponseMessage_FieldNumber_UserGender = 7,
  LoginResponseMessage_FieldNumber_UserAge = 8,
  LoginResponseMessage_FieldNumber_SmokeAge = 9,
  LoginResponseMessage_FieldNumber_UserHeight = 10,
  LoginResponseMessage_FieldNumber_UserWeight = 11,
  LoginResponseMessage_FieldNumber_PlanCount = 12,
  LoginResponseMessage_FieldNumber_PlanTime = 13,
  LoginResponseMessage_FieldNumber_HomeInfo = 14,
  LoginResponseMessage_FieldNumber_Language = 15,
};

@interface LoginResponseMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ErrorMessage *errorMsg;
/// Test to see if @c errorMsg has been set.
@property(nonatomic, readwrite) BOOL hasErrorMsg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *session;

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userPhoto;

@property(nonatomic, readwrite) int32_t userGender;

@property(nonatomic, readwrite) int32_t userAge;

@property(nonatomic, readwrite) int32_t smokeAge;

@property(nonatomic, readwrite) double userHeight;

@property(nonatomic, readwrite) double userWeight;

@property(nonatomic, readwrite) int32_t planCount;

@property(nonatomic, readwrite) int32_t planTime;

@property(nonatomic, readwrite) int32_t homeInfo;

@property(nonatomic, readwrite) int32_t language;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
