// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadSmokingLocationDataRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UploadSmokingLocationDataRequest.pbobjc.h"
 #import "SmokingLocationData.pbobjc.h"
 #import "PhoneType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UploadSmokingLocationDataRequestRoot

@implementation UploadSmokingLocationDataRequestRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[SmokingLocationDataRoot extensionRegistry]];
    [registry addExtensions:[PhoneTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UploadSmokingLocationDataRequestRoot_FileDescriptor

static GPBFileDescriptor *UploadSmokingLocationDataRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UploadSmokingLocationDataRequestMessage

@implementation UploadSmokingLocationDataRequestMessage

@dynamic session;
@dynamic phoneType;
@dynamic smokingLocationDatasArray, smokingLocationDatasArray_Count;

typedef struct UploadSmokingLocationDataRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  PhoneType phoneType;
  NSString *session;
  NSMutableArray *smokingLocationDatasArray;
} UploadSmokingLocationDataRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = UploadSmokingLocationDataRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UploadSmokingLocationDataRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneType",
        .dataTypeSpecific.enumDescFunc = PhoneType_EnumDescriptor,
        .number = UploadSmokingLocationDataRequestMessage_FieldNumber_PhoneType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UploadSmokingLocationDataRequestMessage__storage_, phoneType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "smokingLocationDatasArray",
        .dataTypeSpecific.className = GPBStringifySymbol(SmokingLocationDataMessage),
        .number = UploadSmokingLocationDataRequestMessage_FieldNumber_SmokingLocationDatasArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UploadSmokingLocationDataRequestMessage__storage_, smokingLocationDatasArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UploadSmokingLocationDataRequestMessage class]
                                     rootClass:[UploadSmokingLocationDataRequestRoot class]
                                          file:UploadSmokingLocationDataRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UploadSmokingLocationDataRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\t\000\003\000smokingLocationDatas\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UploadSmokingLocationDataRequestMessage_PhoneType_RawValue(UploadSmokingLocationDataRequestMessage *message) {
  GPBDescriptor *descriptor = [UploadSmokingLocationDataRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UploadSmokingLocationDataRequestMessage_FieldNumber_PhoneType];
  return GPBGetMessageInt32Field(message, field);
}

void SetUploadSmokingLocationDataRequestMessage_PhoneType_RawValue(UploadSmokingLocationDataRequestMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [UploadSmokingLocationDataRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UploadSmokingLocationDataRequestMessage_FieldNumber_PhoneType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
