// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadSmokingLocationDataRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "DownloadSmokingLocationDataRequest.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DownloadSmokingLocationDataRequestRoot

@implementation DownloadSmokingLocationDataRequestRoot

@end

#pragma mark - DownloadSmokingLocationDataRequestRoot_FileDescriptor

static GPBFileDescriptor *DownloadSmokingLocationDataRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - DownloadSmokingLocationDataRequestMessage

@implementation DownloadSmokingLocationDataRequestMessage

@dynamic session;
@dynamic time;

typedef struct DownloadSmokingLocationDataRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *session;
  int64_t time;
} DownloadSmokingLocationDataRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = DownloadSmokingLocationDataRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DownloadSmokingLocationDataRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = DownloadSmokingLocationDataRequestMessage_FieldNumber_Time,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(DownloadSmokingLocationDataRequestMessage__storage_, time),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DownloadSmokingLocationDataRequestMessage class]
                                     rootClass:[DownloadSmokingLocationDataRequestRoot class]
                                          file:DownloadSmokingLocationDataRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DownloadSmokingLocationDataRequestMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
