// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetCommentListRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "GetCommentListRequest.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetCommentListRequestRoot

@implementation GetCommentListRequestRoot

@end

#pragma mark - GetCommentListRequestRoot_FileDescriptor

static GPBFileDescriptor *GetCommentListRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetCommentListRequestMessage

@implementation GetCommentListRequestMessage

@dynamic session;
@dynamic blogId;
@dynamic pageIndex;

typedef struct GetCommentListRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t pageIndex;
  NSString *session;
  int64_t blogId;
} GetCommentListRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = GetCommentListRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetCommentListRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "blogId",
        .dataTypeSpecific.className = NULL,
        .number = GetCommentListRequestMessage_FieldNumber_BlogId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetCommentListRequestMessage__storage_, blogId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "pageIndex",
        .dataTypeSpecific.className = NULL,
        .number = GetCommentListRequestMessage_FieldNumber_PageIndex,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetCommentListRequestMessage__storage_, pageIndex),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetCommentListRequestMessage class]
                                     rootClass:[GetCommentListRequestRoot class]
                                          file:GetCommentListRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetCommentListRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\006\000\003\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
