// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmokingLocationData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SmokingLocationDataRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface SmokingLocationDataRoot : GPBRootObject
@end

#pragma mark - SmokingLocationDataMessage

typedef GPB_ENUM(SmokingLocationDataMessage_FieldNumber) {
  SmokingLocationDataMessage_FieldNumber_SmokingId = 1,
  SmokingLocationDataMessage_FieldNumber_UserId = 2,
  SmokingLocationDataMessage_FieldNumber_SmokingDt = 3,
  SmokingLocationDataMessage_FieldNumber_Longitude = 4,
  SmokingLocationDataMessage_FieldNumber_Latitude = 5,
  SmokingLocationDataMessage_FieldNumber_Address = 6,
  SmokingLocationDataMessage_FieldNumber_WorkMode = 7,
  SmokingLocationDataMessage_FieldNumber_PowerTemp = 8,
  SmokingLocationDataMessage_FieldNumber_SmokingTime = 9,
  SmokingLocationDataMessage_FieldNumber_Battery = 10,
  SmokingLocationDataMessage_FieldNumber_ResistanceValue = 11,
};

@interface SmokingLocationDataMessage : GPBMessage

@property(nonatomic, readwrite) int64_t smokingId;

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite) int64_t smokingDt;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite) int32_t workMode;

@property(nonatomic, readwrite) int32_t powerTemp;

@property(nonatomic, readwrite) int32_t smokingTime;

@property(nonatomic, readwrite) int32_t battery;

@property(nonatomic, readwrite) int32_t resistanceValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
