// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadSmokingDataRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "DownloadSmokingDataRequest.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DownloadSmokingDataRequestRoot

@implementation DownloadSmokingDataRequestRoot

@end

#pragma mark - DownloadSmokingDataRequestRoot_FileDescriptor

static GPBFileDescriptor *DownloadSmokingDataRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - DownloadSmokingDataRequestMessage

@implementation DownloadSmokingDataRequestMessage

@dynamic session;
@dynamic time;

typedef struct DownloadSmokingDataRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *session;
  int64_t time;
} DownloadSmokingDataRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = DownloadSmokingDataRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DownloadSmokingDataRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = DownloadSmokingDataRequestMessage_FieldNumber_Time,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(DownloadSmokingDataRequestMessage__storage_, time),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DownloadSmokingDataRequestMessage class]
                                     rootClass:[DownloadSmokingDataRequestRoot class]
                                          file:DownloadSmokingDataRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DownloadSmokingDataRequestMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
