// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckUpdateRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "CheckUpdateRequest.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CheckUpdateRequestRoot

@implementation CheckUpdateRequestRoot

@end

#pragma mark - CheckUpdateRequestRoot_FileDescriptor

static GPBFileDescriptor *CheckUpdateRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - CheckUpdateRequestMessage

@implementation CheckUpdateRequestMessage

@dynamic appVersion;
@dynamic phoneType;

typedef struct CheckUpdateRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  CheckUpdateRequestMessage_PhoneType phoneType;
  NSString *appVersion;
} CheckUpdateRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "appVersion",
        .dataTypeSpecific.className = NULL,
        .number = CheckUpdateRequestMessage_FieldNumber_AppVersion,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CheckUpdateRequestMessage__storage_, appVersion),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneType",
        .dataTypeSpecific.enumDescFunc = CheckUpdateRequestMessage_PhoneType_EnumDescriptor,
        .number = CheckUpdateRequestMessage_FieldNumber_PhoneType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CheckUpdateRequestMessage__storage_, phoneType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CheckUpdateRequestMessage class]
                                     rootClass:[CheckUpdateRequestRoot class]
                                          file:CheckUpdateRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CheckUpdateRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\n\000\002\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t CheckUpdateRequestMessage_PhoneType_RawValue(CheckUpdateRequestMessage *message) {
  GPBDescriptor *descriptor = [CheckUpdateRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:CheckUpdateRequestMessage_FieldNumber_PhoneType];
  return GPBGetMessageInt32Field(message, field);
}

void SetCheckUpdateRequestMessage_PhoneType_RawValue(CheckUpdateRequestMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [CheckUpdateRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:CheckUpdateRequestMessage_FieldNumber_PhoneType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum CheckUpdateRequestMessage_PhoneType

GPBEnumDescriptor *CheckUpdateRequestMessage_PhoneType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "IPhone\000AndroidPhone\000";
    static const int32_t values[] = {
        CheckUpdateRequestMessage_PhoneType_IPhone,
        CheckUpdateRequestMessage_PhoneType_AndroidPhone,
    };
    static const char *extraTextFormatInfo = "\002\000&\000\001\014\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CheckUpdateRequestMessage_PhoneType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:CheckUpdateRequestMessage_PhoneType_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL CheckUpdateRequestMessage_PhoneType_IsValidValue(int32_t value__) {
  switch (value__) {
    case CheckUpdateRequestMessage_PhoneType_IPhone:
    case CheckUpdateRequestMessage_PhoneType_AndroidPhone:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
