// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetCommentListResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CommentMessage;
@class ErrorMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GetCommentListResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface GetCommentListResponseRoot : GPBRootObject
@end

#pragma mark - GetCommentListResponseMessage

typedef GPB_ENUM(GetCommentListResponseMessage_FieldNumber) {
  GetCommentListResponseMessage_FieldNumber_ErrorMsg = 1,
  GetCommentListResponseMessage_FieldNumber_IsLastPage = 2,
  GetCommentListResponseMessage_FieldNumber_CommentsArray = 3,
};

@interface GetCommentListResponseMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ErrorMessage *errorMsg;
/// Test to see if @c errorMsg has been set.
@property(nonatomic, readwrite) BOOL hasErrorMsg;

@property(nonatomic, readwrite) BOOL isLastPage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CommentMessage*> *commentsArray;
/// The number of items in @c commentsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger commentsArray_Count;

@end

#pragma mark - CommentMessage

typedef GPB_ENUM(CommentMessage_FieldNumber) {
  CommentMessage_FieldNumber_Content = 1,
  CommentMessage_FieldNumber_CommentId = 2,
  CommentMessage_FieldNumber_UserId = 3,
  CommentMessage_FieldNumber_Author = 4,
  CommentMessage_FieldNumber_AuthorPhoto = 5,
  CommentMessage_FieldNumber_CreateDt = 6,
  CommentMessage_FieldNumber_ImagesArray = 7,
};

@interface CommentMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) int64_t commentId;

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *author;

@property(nonatomic, readwrite, copy, null_resettable) NSString *authorPhoto;

@property(nonatomic, readwrite) int64_t createDt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *imagesArray;
/// The number of items in @c imagesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
