// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckUpdateRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CheckUpdateRequestMessage_PhoneType

typedef GPB_ENUM(CheckUpdateRequestMessage_PhoneType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  CheckUpdateRequestMessage_PhoneType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CheckUpdateRequestMessage_PhoneType_IPhone = 0,
  CheckUpdateRequestMessage_PhoneType_AndroidPhone = 1,
};

GPBEnumDescriptor *CheckUpdateRequestMessage_PhoneType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL CheckUpdateRequestMessage_PhoneType_IsValidValue(int32_t value);

#pragma mark - CheckUpdateRequestRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface CheckUpdateRequestRoot : GPBRootObject
@end

#pragma mark - CheckUpdateRequestMessage

typedef GPB_ENUM(CheckUpdateRequestMessage_FieldNumber) {
  CheckUpdateRequestMessage_FieldNumber_AppVersion = 1,
  CheckUpdateRequestMessage_FieldNumber_PhoneType = 2,
};

@interface CheckUpdateRequestMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appVersion;

@property(nonatomic, readwrite) CheckUpdateRequestMessage_PhoneType phoneType;

@end

/// Fetches the raw value of a @c CheckUpdateRequestMessage's @c phoneType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t CheckUpdateRequestMessage_PhoneType_RawValue(CheckUpdateRequestMessage *message);
/// Sets the raw value of an @c CheckUpdateRequestMessage's @c phoneType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetCheckUpdateRequestMessage_PhoneType_RawValue(CheckUpdateRequestMessage *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
