// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "RegisterRequest.pbobjc.h"
 #import "PhoneType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - RegisterRequestRoot

@implementation RegisterRequestRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[PhoneTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - RegisterRequestRoot_FileDescriptor

static GPBFileDescriptor *RegisterRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - RegisterRequestMessage

@implementation RegisterRequestMessage

@dynamic phone;
@dynamic password;
@dynamic phoneType;

typedef struct RegisterRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  PhoneType phoneType;
  NSString *phone;
  NSString *password;
} RegisterRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "phone",
        .dataTypeSpecific.className = NULL,
        .number = RegisterRequestMessage_FieldNumber_Phone,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RegisterRequestMessage__storage_, phone),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "password",
        .dataTypeSpecific.className = NULL,
        .number = RegisterRequestMessage_FieldNumber_Password,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RegisterRequestMessage__storage_, password),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneType",
        .dataTypeSpecific.enumDescFunc = PhoneType_EnumDescriptor,
        .number = RegisterRequestMessage_FieldNumber_PhoneType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RegisterRequestMessage__storage_, phoneType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RegisterRequestMessage class]
                                     rootClass:[RegisterRequestRoot class]
                                          file:RegisterRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RegisterRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RegisterRequestMessage_PhoneType_RawValue(RegisterRequestMessage *message) {
  GPBDescriptor *descriptor = [RegisterRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RegisterRequestMessage_FieldNumber_PhoneType];
  return GPBGetMessageInt32Field(message, field);
}

void SetRegisterRequestMessage_PhoneType_RawValue(RegisterRequestMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [RegisterRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RegisterRequestMessage_FieldNumber_PhoneType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
