// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UploadSmokingDataRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "UploadSmokingDataRequest.pbobjc.h"
 #import "SmokingData.pbobjc.h"
 #import "PhoneType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UploadSmokingDataRequestRoot

@implementation UploadSmokingDataRequestRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[SmokingDataRoot extensionRegistry]];
    [registry addExtensions:[PhoneTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UploadSmokingDataRequestRoot_FileDescriptor

static GPBFileDescriptor *UploadSmokingDataRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UploadSmokingDataRequestMessage

@implementation UploadSmokingDataRequestMessage

@dynamic session;
@dynamic phoneType;
@dynamic smokingDatasArray, smokingDatasArray_Count;

typedef struct UploadSmokingDataRequestMessage__storage_ {
  uint32_t _has_storage_[1];
  PhoneType phoneType;
  NSString *session;
  NSMutableArray *smokingDatasArray;
} UploadSmokingDataRequestMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = UploadSmokingDataRequestMessage_FieldNumber_Session,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UploadSmokingDataRequestMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneType",
        .dataTypeSpecific.enumDescFunc = PhoneType_EnumDescriptor,
        .number = UploadSmokingDataRequestMessage_FieldNumber_PhoneType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UploadSmokingDataRequestMessage__storage_, phoneType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "smokingDatasArray",
        .dataTypeSpecific.className = GPBStringifySymbol(SmokingDataMessage),
        .number = UploadSmokingDataRequestMessage_FieldNumber_SmokingDatasArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UploadSmokingDataRequestMessage__storage_, smokingDatasArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UploadSmokingDataRequestMessage class]
                                     rootClass:[UploadSmokingDataRequestRoot class]
                                          file:UploadSmokingDataRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UploadSmokingDataRequestMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\t\000\003\000smokingDatas\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UploadSmokingDataRequestMessage_PhoneType_RawValue(UploadSmokingDataRequestMessage *message) {
  GPBDescriptor *descriptor = [UploadSmokingDataRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UploadSmokingDataRequestMessage_FieldNumber_PhoneType];
  return GPBGetMessageInt32Field(message, field);
}

void SetUploadSmokingDataRequestMessage_PhoneType_RawValue(UploadSmokingDataRequestMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [UploadSmokingDataRequestMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UploadSmokingDataRequestMessage_FieldNumber_PhoneType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
