// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetBlogListResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BlogMessage;
@class ErrorMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GetBlogListResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface GetBlogListResponseRoot : GPBRootObject
@end

#pragma mark - GetBlogListResponseMessage

typedef GPB_ENUM(GetBlogListResponseMessage_FieldNumber) {
  GetBlogListResponseMessage_FieldNumber_ErrorMsg = 1,
  GetBlogListResponseMessage_FieldNumber_IsLastPage = 2,
  GetBlogListResponseMessage_FieldNumber_BlogsArray = 3,
};

@interface GetBlogListResponseMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ErrorMessage *errorMsg;
/// Test to see if @c errorMsg has been set.
@property(nonatomic, readwrite) BOOL hasErrorMsg;

@property(nonatomic, readwrite) BOOL isLastPage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BlogMessage*> *blogsArray;
/// The number of items in @c blogsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger blogsArray_Count;

@end

#pragma mark - BlogMessage

typedef GPB_ENUM(BlogMessage_FieldNumber) {
  BlogMessage_FieldNumber_BlogId = 1,
  BlogMessage_FieldNumber_Content = 2,
  BlogMessage_FieldNumber_Longitude = 3,
  BlogMessage_FieldNumber_Latitude = 4,
  BlogMessage_FieldNumber_Address = 5,
  BlogMessage_FieldNumber_LikeCount = 6,
  BlogMessage_FieldNumber_CommentCount = 7,
  BlogMessage_FieldNumber_UserId = 8,
  BlogMessage_FieldNumber_IsLike = 9,
  BlogMessage_FieldNumber_Author = 10,
  BlogMessage_FieldNumber_AuthorPhoto = 11,
  BlogMessage_FieldNumber_CreateDt = 12,
  BlogMessage_FieldNumber_ImagesArray = 13,
};

@interface BlogMessage : GPBMessage

@property(nonatomic, readwrite) int64_t blogId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite) int32_t likeCount;

@property(nonatomic, readwrite) int32_t commentCount;

@property(nonatomic, readwrite) int64_t userId;

@property(nonatomic, readwrite) BOOL isLike;

@property(nonatomic, readwrite, copy, null_resettable) NSString *author;

@property(nonatomic, readwrite, copy, null_resettable) NSString *authorPhoto;

@property(nonatomic, readwrite) int64_t createDt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *imagesArray;
/// The number of items in @c imagesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
