// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DownloadHeartRateDataResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "DownloadHeartRateDataResponse.pbobjc.h"
 #import "ErrorMessageResponse.pbobjc.h"
 #import "HeartRateData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - DownloadHeartRateDataResponseRoot

@implementation DownloadHeartRateDataResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ErrorMessageResponseRoot extensionRegistry]];
    [registry addExtensions:[HeartRateDataRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - DownloadHeartRateDataResponseRoot_FileDescriptor

static GPBFileDescriptor *DownloadHeartRateDataResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - DownloadHeartRateDataResponseMessage

@implementation DownloadHeartRateDataResponseMessage

@dynamic hasErrorMsg, errorMsg;
@dynamic heartRateDatasArray, heartRateDatasArray_Count;

typedef struct DownloadHeartRateDataResponseMessage__storage_ {
  uint32_t _has_storage_[1];
  ErrorMessage *errorMsg;
  NSMutableArray *heartRateDatasArray;
} DownloadHeartRateDataResponseMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "errorMsg",
        .dataTypeSpecific.className = GPBStringifySymbol(ErrorMessage),
        .number = DownloadHeartRateDataResponseMessage_FieldNumber_ErrorMsg,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(DownloadHeartRateDataResponseMessage__storage_, errorMsg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "heartRateDatasArray",
        .dataTypeSpecific.className = GPBStringifySymbol(HeartRateDataMessage),
        .number = DownloadHeartRateDataResponseMessage_FieldNumber_HeartRateDatasArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(DownloadHeartRateDataResponseMessage__storage_, heartRateDatasArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[DownloadHeartRateDataResponseMessage class]
                                     rootClass:[DownloadHeartRateDataResponseRoot class]
                                          file:DownloadHeartRateDataResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(DownloadHeartRateDataResponseMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\010\000\002\000heartRateDatas\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
