// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "LoginResponse.pbobjc.h"
 #import "ErrorMessageResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - LoginResponseRoot

@implementation LoginResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ErrorMessageResponseRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - LoginResponseRoot_FileDescriptor

static GPBFileDescriptor *LoginResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - LoginResponseMessage

@implementation LoginResponseMessage

@dynamic hasErrorMsg, errorMsg;
@dynamic session;
@dynamic userId;
@dynamic phone;
@dynamic userName;
@dynamic userPhoto;
@dynamic userGender;
@dynamic userAge;
@dynamic smokeAge;
@dynamic userHeight;
@dynamic userWeight;
@dynamic planCount;
@dynamic planTime;
@dynamic homeInfo;
@dynamic language;

typedef struct LoginResponseMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t userGender;
  int32_t userAge;
  int32_t smokeAge;
  int32_t planCount;
  int32_t planTime;
  int32_t homeInfo;
  int32_t language;
  ErrorMessage *errorMsg;
  NSString *session;
  NSString *phone;
  NSString *userName;
  NSString *userPhoto;
  int64_t userId;
  double userHeight;
  double userWeight;
} LoginResponseMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "errorMsg",
        .dataTypeSpecific.className = GPBStringifySymbol(ErrorMessage),
        .number = LoginResponseMessage_FieldNumber_ErrorMsg,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, errorMsg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "session",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_Session,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, session),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "phone",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_Phone,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, phone),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userName",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userPhoto",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserPhoto,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userPhoto),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userGender",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserGender,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userGender),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "userAge",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserAge,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userAge),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "smokeAge",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_SmokeAge,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, smokeAge),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "userHeight",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserHeight,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userHeight),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "userWeight",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_UserWeight,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, userWeight),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "planCount",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_PlanCount,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, planCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "planTime",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_PlanTime,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, planTime),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "homeInfo",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_HomeInfo,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, homeInfo),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "language",
        .dataTypeSpecific.className = NULL,
        .number = LoginResponseMessage_FieldNumber_Language,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(LoginResponseMessage__storage_, language),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[LoginResponseMessage class]
                                     rootClass:[LoginResponseRoot class]
                                          file:LoginResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(LoginResponseMessage__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\014\001\010\000\003\006\000\005\010\000\006\t\000\007\n\000\010\007\000\t\010\000\n\n\000\013\n\000\014\t\000\r\010\000\016\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
